{% set name = "diode" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/diode-{{ version }}.tar.gz
  sha256: a87bf38e625e9d363ec7591cfa27cf894418b1a9e26f74c4239690ff03bd0b4f

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<312]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=2                              # [build_platform != target_platform]
  host:
    - pip
    - python
    - cgal-cpp
    - python
    - scikit-build-core
    - pybind11
    - gmp
    - mpfr
    - numpy >=2.3.5
  run:
    - python


test:
  imports:
    - diode
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mrzv/diode
  summary: alpha shape generator using CGAL
  license: GPL-2.0-or-later
  license_file:
    - LICENSE
    - vendor-licenses/

extra:
  recipe-maintainers:
    - mrzv
    - kjappelbaum
