{% set name = "diode" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/diode-{{ version }}.tar.gz
  sha256: 4fcb2ca63a6e05de309e885b2a4cfd5b0ea86d624c7b25fe63231d570069489b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<312]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pip
    - python
    - cgal-cpp
    - python
    - scikit-build-core
    - pybind11
    - gmp
    - mpfr
    - numpy >=2.3.5
  run:
    - python


test:
  imports:
    - diode
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mrzv/diode
  summary: alpha shape generator using CGAL
  license: GPL-2.0-or-later
  license_file:
    - LICENSE
    - vendor-licenses/

extra:
  recipe-maintainers:
    - mrzv
    - kjappelbaum
