{% set name = "diode" %}
{% set version = "1.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/diode-{{ version }}.tar.gz
  sha256: e3d2d8cee789cf7db5754528d4828a3b3a1c3807d55136368cf716444e284930

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<312]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=2                              # [build_platform != target_platform]
  host:
    - pip
    - python
    - cgal-cpp
    - python
    - scikit-build-core
    - pybind11
    - gmp
    - mpfr
    - numpy >=2.3.5
  run:
    - python


test:
  imports:
    - diode
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mrzv/diode
  summary: alpha shape generator using CGAL
  license: GPL-2.0-or-later
  license_file:
    - LICENSE
    - vendor-licenses/

extra:
  recipe-maintainers:
    - mrzv
    - kjappelbaum
